[[countries]]
country = "Afghanistan"
alpha2 = "AF"
alpha3 = "AFG"
num = 4

[[countries]]
country = "Albania"
alpha2 = "AL"
alpha3 = "ALB"
num = 8

[[countries]]
country = "Algeria"
alpha2 = "DZ"
alpha3 = "DZA"
num = 12

[[countries]]
country = "American Samoa"
alpha2 = "AS"
alpha3 = "ASM"
num = 16

[[countries]]
country = "Andorra"
alpha2 = "AD"
alpha3 = "AND"
num = 20

[[countries]]
country = "Angola"
alpha2 = "AO"
alpha3 = "AGO"
num = 24

[[countries]]
country = "Anguilla"
alpha2 = "AI"
alpha3 = "AIA"
num = 660

[[countries]]
country = "Antarctica"
alpha2 = "AQ"
alpha3 = "ATA"
num = 10

[[countries]]
country = "Antigua and Barbuda"
alpha2 = "AG"
alpha3 = "ATG"
num = 28

[[countries]]
country = "Argentina"
alpha2 = "AR"
alpha3 = "ARG"
num = 32

[[countries]]
country = "Armenia"
alpha2 = "AM"
alpha3 = "ARM"
num = 51

[[countries]]
country = "Aruba"
alpha2 = "AW"
alpha3 = "ABW"
num = 533

[[countries]]
country = "Australia"
alpha2 = "AU"
alpha3 = "AUS"
num = 36

[[countries]]
country = "Austria"
alpha2 = "AT"
alpha3 = "AUT"
num = 40

[[countries]]
country = "Azerbaijan"
alpha2 = "AZ"
alpha3 = "AZE"
num = 31

[[countries]]
country = "Bahamas (the)"
alpha2 = "BS"
alpha3 = "BHS"
num = 44

[[countries]]
country = "Bahrain"
alpha2 = "BH"
alpha3 = "BHR"
num = 48

[[countries]]
country = "Bangladesh"
alpha2 = "BD"
alpha3 = "BGD"
num = 50

[[countries]]
country = "Barbados"
alpha2 = "BB"
alpha3 = "BRB"
num = 52

[[countries]]
country = "Belarus"
alpha2 = "BY"
alpha3 = "BLR"
num = 112

[[countries]]
country = "Belgium"
alpha2 = "BE"
alpha3 = "BEL"
num = 56

[[countries]]
country = "Belize"
alpha2 = "BZ"
alpha3 = "BLZ"
num = 84

[[countries]]
country = "Benin"
alpha2 = "BJ"
alpha3 = "BEN"
num = 204

[[countries]]
country = "Bermuda"
alpha2 = "BM"
alpha3 = "BMU"
num = 60

[[countries]]
country = "Bhutan"
alpha2 = "BT"
alpha3 = "BTN"
num = 64

[[countries]]
country = "Bolivia (Plurinational State of)"
alpha2 = "BO"
alpha3 = "BOL"
num = 68

[[countries]]
country = "Bonaire, Sint Eustatius and Saba"
alpha2 = "BQ"
alpha3 = "BES"
num = 535

[[countries]]
country = "Bosnia and Herzegovina"
alpha2 = "BA"
alpha3 = "BIH"
num = 70

[[countries]]
country = "Botswana"
alpha2 = "BW"
alpha3 = "BWA"
num = 72

[[countries]]
country = "Bouvet Island"
alpha2 = "BV"
alpha3 = "BVT"
num = 74

[[countries]]
country = "Brazil"
alpha2 = "BR"
alpha3 = "BRA"
num = 76

[[countries]]
country = "British Indian Ocean Territory (the)"
alpha2 = "IO"
alpha3 = "IOT"
num = 86

[[countries]]
country = "Brunei Darussalam"
alpha2 = "BN"
alpha3 = "BRN"
num = 96

[[countries]]
country = "Bulgaria"
alpha2 = "BG"
alpha3 = "BGR"
num = 100

[[countries]]
country = "Burkina Faso"
alpha2 = "BF"
alpha3 = "BFA"
num = 854

[[countries]]
country = "Burundi"
alpha2 = "BI"
alpha3 = "BDI"
num = 108

[[countries]]
country = "Cabo Verde"
alpha2 = "CV"
alpha3 = "CPV"
num = 132

[[countries]]
country = "Cambodia"
alpha2 = "KH"
alpha3 = "KHM"
num = 116

[[countries]]
country = "Cameroon"
alpha2 = "CM"
alpha3 = "CMR"
num = 120

[[countries]]
country = "Canada"
alpha2 = "CA"
alpha3 = "CAN"
num = 124

[[countries]]
country = "Cayman Islands (the)"
alpha2 = "KY"
alpha3 = "CYM"
num = 136

[[countries]]
country = "Central African Republic (the)"
alpha2 = "CF"
alpha3 = "CAF"
num = 140

[[countries]]
country = "Chad"
alpha2 = "TD"
alpha3 = "TCD"
num = 148

[[countries]]
country = "Chile"
alpha2 = "CL"
alpha3 = "CHL"
num = 152

[[countries]]
country = "China"
alpha2 = "CN"
alpha3 = "CHN"
num = 156

[[countries]]
country = "Christmas Island"
alpha2 = "CX"
alpha3 = "CXR"
num = 162

[[countries]]
country = "Cocos (Keeling) Islands (the)"
alpha2 = "CC"
alpha3 = "CCK"
num = 166

[[countries]]
country = "Colombia"
alpha2 = "CO"
alpha3 = "COL"
num = 170

[[countries]]
country = "Comoros (the)"
alpha2 = "KM"
alpha3 = "COM"
num = 174

[[countries]]
country = "Congo (the Democratic Republic of the)"
alpha2 = "CD"
alpha3 = "COD"
num = 180

[[countries]]
country = "Congo (the)"
alpha2 = "CG"
alpha3 = "COG"
num = 178

[[countries]]
country = "Cook Islands (the)"
alpha2 = "CK"
alpha3 = "COK"
num = 184

[[countries]]
country = "Costa Rica"
alpha2 = "CR"
alpha3 = "CRI"
num = 188

[[countries]]
country = "Croatia"
alpha2 = "HR"
alpha3 = "HRV"
num = 191

[[countries]]
country = "Cuba"
alpha2 = "CU"
alpha3 = "CUB"
num = 192

[[countries]]
country = "Curaçao"
alpha2 = "CW"
alpha3 = "CUW"
num = 531

[[countries]]
country = "Cyprus"
alpha2 = "CY"
alpha3 = "CYP"
num = 196

[[countries]]
country = "Czechia"
alpha2 = "CZ"
alpha3 = "CZE"
num = 203

[[countries]]
country = "Côte d'Ivoire"
alpha2 = "CI"
alpha3 = "CIV"
num = 384

[[countries]]
country = "Denmark"
alpha2 = "DK"
alpha3 = "DNK"
num = 208

[[countries]]
country = "Djibouti"
alpha2 = "DJ"
alpha3 = "DJI"
num = 262

[[countries]]
country = "Dominica"
alpha2 = "DM"
alpha3 = "DMA"
num = 212

[[countries]]
country = "Dominican Republic (the)"
alpha2 = "DO"
alpha3 = "DOM"
num = 214

[[countries]]
country = "Ecuador"
alpha2 = "EC"
alpha3 = "ECU"
num = 218

[[countries]]
country = "Egypt"
alpha2 = "EG"
alpha3 = "EGY"
num = 818

[[countries]]
country = "El Salvador"
alpha2 = "SV"
alpha3 = "SLV"
num = 222

[[countries]]
country = "Equatorial Guinea"
alpha2 = "GQ"
alpha3 = "GNQ"
num = 226

[[countries]]
country = "Eritrea"
alpha2 = "ER"
alpha3 = "ERI"
num = 232

[[countries]]
country = "Estonia"
alpha2 = "EE"
alpha3 = "EST"
num = 233

[[countries]]
country = "Eswatini"
alpha2 = "SZ"
alpha3 = "SWZ"
num = 748

[[countries]]
country = "Ethiopia"
alpha2 = "ET"
alpha3 = "ETH"
num = 231

[[countries]]
country = "Falkland Islands (the) [Malvinas]"
alpha2 = "FK"
alpha3 = "FLK"
num = 238

[[countries]]
country = "Faroe Islands (the)"
alpha2 = "FO"
alpha3 = "FRO"
num = 234

[[countries]]
country = "Fiji"
alpha2 = "FJ"
alpha3 = "FJI"
num = 242

[[countries]]
country = "Finland"
alpha2 = "FI"
alpha3 = "FIN"
num = 246

[[countries]]
country = "France"
alpha2 = "FR"
alpha3 = "FRA"
num = 250

[[countries]]
country = "French Guiana"
alpha2 = "GF"
alpha3 = "GUF"
num = 254

[[countries]]
country = "French Polynesia"
alpha2 = "PF"
alpha3 = "PYF"
num = 258

[[countries]]
country = "French Southern Territories (the)"
alpha2 = "TF"
alpha3 = "ATF"
num = 260

[[countries]]
country = "Gabon"
alpha2 = "GA"
alpha3 = "GAB"
num = 266

[[countries]]
country = "Gambia (the)"
alpha2 = "GM"
alpha3 = "GMB"
num = 270

[[countries]]
country = "Georgia"
alpha2 = "GE"
alpha3 = "GEO"
num = 268

[[countries]]
country = "Germany"
alpha2 = "DE"
alpha3 = "DEU"
num = 276

[[countries]]
country = "Ghana"
alpha2 = "GH"
alpha3 = "GHA"
num = 288

[[countries]]
country = "Gibraltar"
alpha2 = "GI"
alpha3 = "GIB"
num = 292

[[countries]]
country = "Greece"
alpha2 = "GR"
alpha3 = "GRC"
num = 300

[[countries]]
country = "Greenland"
alpha2 = "GL"
alpha3 = "GRL"
num = 304

[[countries]]
country = "Grenada"
alpha2 = "GD"
alpha3 = "GRD"
num = 308

[[countries]]
country = "Guadeloupe"
alpha2 = "GP"
alpha3 = "GLP"
num = 312

[[countries]]
country = "Guam"
alpha2 = "GU"
alpha3 = "GUM"
num = 316

[[countries]]
country = "Guatemala"
alpha2 = "GT"
alpha3 = "GTM"
num = 320

[[countries]]
country = "Guernsey"
alpha2 = "GG"
alpha3 = "GGY"
num = 831

[[countries]]
country = "Guinea"
alpha2 = "GN"
alpha3 = "GIN"
num = 324

[[countries]]
country = "Guinea-Bissau"
alpha2 = "GW"
alpha3 = "GNB"
num = 624

[[countries]]
country = "Guyana"
alpha2 = "GY"
alpha3 = "GUY"
num = 328

[[countries]]
country = "Haiti"
alpha2 = "HT"
alpha3 = "HTI"
num = 332

[[countries]]
country = "Heard Island and McDonald Islands"
alpha2 = "HM"
alpha3 = "HMD"
num = 334

[[countries]]
country = "Holy See (the)"
alpha2 = "VA"
alpha3 = "VAT"
num = 336

[[countries]]
country = "Honduras"
alpha2 = "HN"
alpha3 = "HND"
num = 340

[[countries]]
country = "Hong Kong"
alpha2 = "HK"
alpha3 = "HKG"
num = 344

[[countries]]
country = "Hungary"
alpha2 = "HU"
alpha3 = "HUN"
num = 348

[[countries]]
country = "Iceland"
alpha2 = "IS"
alpha3 = "ISL"
num = 352

[[countries]]
country = "India"
alpha2 = "IN"
alpha3 = "IND"
num = 356

[[countries]]
country = "Indonesia"
alpha2 = "ID"
alpha3 = "IDN"
num = 360

[[countries]]
country = "Iran (Islamic Republic of)"
alpha2 = "IR"
alpha3 = "IRN"
num = 364

[[countries]]
country = "Iraq"
alpha2 = "IQ"
alpha3 = "IRQ"
num = 368

[[countries]]
country = "Ireland"
alpha2 = "IE"
alpha3 = "IRL"
num = 372

[[countries]]
country = "Isle of Man"
alpha2 = "IM"
alpha3 = "IMN"
num = 833

[[countries]]
country = "Israel"
alpha2 = "IL"
alpha3 = "ISR"
num = 376

[[countries]]
country = "Italy"
alpha2 = "IT"
alpha3 = "ITA"
num = 380

[[countries]]
country = "Jamaica"
alpha2 = "JM"
alpha3 = "JAM"
num = 388

[[countries]]
country = "Japan"
alpha2 = "JP"
alpha3 = "JPN"
num = 392

[[countries]]
country = "Jersey"
alpha2 = "JE"
alpha3 = "JEY"
num = 832

[[countries]]
country = "Jordan"
alpha2 = "JO"
alpha3 = "JOR"
num = 400

[[countries]]
country = "Kazakhstan"
alpha2 = "KZ"
alpha3 = "KAZ"
num = 398

[[countries]]
country = "Kenya"
alpha2 = "KE"
alpha3 = "KEN"
num = 404

[[countries]]
country = "Kiribati"
alpha2 = "KI"
alpha3 = "KIR"
num = 296

[[countries]]
country = "Korea (the Democratic People's Republic of)"
alpha2 = "KP"
alpha3 = "PRK"
num = 408

[[countries]]
country = "Korea (the Republic of)"
alpha2 = "KR"
alpha3 = "KOR"
num = 410

[[countries]]
country = "Kuwait"
alpha2 = "KW"
alpha3 = "KWT"
num = 414

[[countries]]
country = "Kyrgyzstan"
alpha2 = "KG"
alpha3 = "KGZ"
num = 417

[[countries]]
country = "Lao People's Democratic Republic (the)"
alpha2 = "LA"
alpha3 = "LAO"
num = 418

[[countries]]
country = "Latvia"
alpha2 = "LV"
alpha3 = "LVA"
num = 428

[[countries]]
country = "Lebanon"
alpha2 = "LB"
alpha3 = "LBN"
num = 422

[[countries]]
country = "Lesotho"
alpha2 = "LS"
alpha3 = "LSO"
num = 426

[[countries]]
country = "Liberia"
alpha2 = "LR"
alpha3 = "LBR"
num = 430

[[countries]]
country = "Libya"
alpha2 = "LY"
alpha3 = "LBY"
num = 434

[[countries]]
country = "Liechtenstein"
alpha2 = "LI"
alpha3 = "LIE"
num = 438

[[countries]]
country = "Lithuania"
alpha2 = "LT"
alpha3 = "LTU"
num = 440

[[countries]]
country = "Luxembourg"
alpha2 = "LU"
alpha3 = "LUX"
num = 442

[[countries]]
country = "Macao"
alpha2 = "MO"
alpha3 = "MAC"
num = 446

[[countries]]
country = "Madagascar"
alpha2 = "MG"
alpha3 = "MDG"
num = 450

[[countries]]
country = "Malawi"
alpha2 = "MW"
alpha3 = "MWI"
num = 454

[[countries]]
country = "Malaysia"
alpha2 = "MY"
alpha3 = "MYS"
num = 458

[[countries]]
country = "Maldives"
alpha2 = "MV"
alpha3 = "MDV"
num = 462

[[countries]]
country = "Mali"
alpha2 = "ML"
alpha3 = "MLI"
num = 466

[[countries]]
country = "Malta"
alpha2 = "MT"
alpha3 = "MLT"
num = 470

[[countries]]
country = "Marshall Islands (the)"
alpha2 = "MH"
alpha3 = "MHL"
num = 584

[[countries]]
country = "Martinique"
alpha2 = "MQ"
alpha3 = "MTQ"
num = 474

[[countries]]
country = "Mauritania"
alpha2 = "MR"
alpha3 = "MRT"
num = 478

[[countries]]
country = "Mauritius"
alpha2 = "MU"
alpha3 = "MUS"
num = 480

[[countries]]
country = "Mayotte"
alpha2 = "YT"
alpha3 = "MYT"
num = 175

[[countries]]
country = "Mexico"
alpha2 = "MX"
alpha3 = "MEX"
num = 484

[[countries]]
country = "Micronesia (Federated States of)"
alpha2 = "FM"
alpha3 = "FSM"
num = 583

[[countries]]
country = "Moldova (the Republic of)"
alpha2 = "MD"
alpha3 = "MDA"
num = 498

[[countries]]
country = "Monaco"
alpha2 = "MC"
alpha3 = "MCO"
num = 492

[[countries]]
country = "Mongolia"
alpha2 = "MN"
alpha3 = "MNG"
num = 496

[[countries]]
country = "Montenegro"
alpha2 = "ME"
alpha3 = "MNE"
num = 499

[[countries]]
country = "Montserrat"
alpha2 = "MS"
alpha3 = "MSR"
num = 500

[[countries]]
country = "Morocco"
alpha2 = "MA"
alpha3 = "MAR"
num = 504

[[countries]]
country = "Mozambique"
alpha2 = "MZ"
alpha3 = "MOZ"
num = 508

[[countries]]
country = "Myanmar"
alpha2 = "MM"
alpha3 = "MMR"
num = 104

[[countries]]
country = "Namibia"
alpha2 = "NA"
alpha3 = "NAM"
num = 516

[[countries]]
country = "Nauru"
alpha2 = "NR"
alpha3 = "NRU"
num = 520

[[countries]]
country = "Nepal"
alpha2 = "NP"
alpha3 = "NPL"
num = 524

[[countries]]
country = "Netherlands (the)"
alpha2 = "NL"
alpha3 = "NLD"
num = 528

[[countries]]
country = "New Caledonia"
alpha2 = "NC"
alpha3 = "NCL"
num = 540

[[countries]]
country = "New Zealand"
alpha2 = "NZ"
alpha3 = "NZL"
num = 554

[[countries]]
country = "Nicaragua"
alpha2 = "NI"
alpha3 = "NIC"
num = 558

[[countries]]
country = "Niger (the)"
alpha2 = "NE"
alpha3 = "NER"
num = 562

[[countries]]
country = "Nigeria"
alpha2 = "NG"
alpha3 = "NGA"
num = 566

[[countries]]
country = "Niue"
alpha2 = "NU"
alpha3 = "NIU"
num = 570

[[countries]]
country = "Norfolk Island"
alpha2 = "NF"
alpha3 = "NFK"
num = 574

[[countries]]
country = "Northern Mariana Islands (the)"
alpha2 = "MP"
alpha3 = "MNP"
num = 580

[[countries]]
country = "Norway"
alpha2 = "NO"
alpha3 = "NOR"
num = 578

[[countries]]
country = "Oman"
alpha2 = "OM"
alpha3 = "OMN"
num = 512

[[countries]]
country = "Pakistan"
alpha2 = "PK"
alpha3 = "PAK"
num = 586

[[countries]]
country = "Palau"
alpha2 = "PW"
alpha3 = "PLW"
num = 585

[[countries]]
country = "Palestine, State of"
alpha2 = "PS"
alpha3 = "PSE"
num = 275

[[countries]]
country = "Panama"
alpha2 = "PA"
alpha3 = "PAN"
num = 591

[[countries]]
country = "Papua New Guinea"
alpha2 = "PG"
alpha3 = "PNG"
num = 598

[[countries]]
country = "Paraguay"
alpha2 = "PY"
alpha3 = "PRY"
num = 600

[[countries]]
country = "Peru"
alpha2 = "PE"
alpha3 = "PER"
num = 604

[[countries]]
country = "Philippines (the)"
alpha2 = "PH"
alpha3 = "PHL"
num = 608

[[countries]]
country = "Pitcairn"
alpha2 = "PN"
alpha3 = "PCN"
num = 612

[[countries]]
country = "Poland"
alpha2 = "PL"
alpha3 = "POL"
num = 616

[[countries]]
country = "Portugal"
alpha2 = "PT"
alpha3 = "PRT"
num = 620

[[countries]]
country = "Puerto Rico"
alpha2 = "PR"
alpha3 = "PRI"
num = 630

[[countries]]
country = "Qatar"
alpha2 = "QA"
alpha3 = "QAT"
num = 634

[[countries]]
country = "Republic of North Macedonia"
alpha2 = "MK"
alpha3 = "MKD"
num = 807

[[countries]]
country = "Romania"
alpha2 = "RO"
alpha3 = "ROU"
num = 642

[[countries]]
country = "Russian Federation (the)"
alpha2 = "RU"
alpha3 = "RUS"
num = 643

[[countries]]
country = "Rwanda"
alpha2 = "RW"
alpha3 = "RWA"
num = 646

[[countries]]
country = "Réunion"
alpha2 = "RE"
alpha3 = "REU"
num = 638

[[countries]]
country = "Saint Barthélemy"
alpha2 = "BL"
alpha3 = "BLM"
num = 652

[[countries]]
country = "Saint Helena, Ascension and Tristan da Cunha"
alpha2 = "SH"
alpha3 = "SHN"
num = 654

[[countries]]
country = "Saint Kitts and Nevis"
alpha2 = "KN"
alpha3 = "KNA"
num = 659

[[countries]]
country = "Saint Lucia"
alpha2 = "LC"
alpha3 = "LCA"
num = 662

[[countries]]
country = "Saint Martin (French part)"
alpha2 = "MF"
alpha3 = "MAF"
num = 663

[[countries]]
country = "Saint Pierre and Miquelon"
alpha2 = "PM"
alpha3 = "SPM"
num = 666

[[countries]]
country = "Saint Vincent and the Grenadines"
alpha2 = "VC"
alpha3 = "VCT"
num = 670

[[countries]]
country = "Samoa"
alpha2 = "WS"
alpha3 = "WSM"
num = 882

[[countries]]
country = "San Marino"
alpha2 = "SM"
alpha3 = "SMR"
num = 674

[[countries]]
country = "Sao Tome and Principe"
alpha2 = "ST"
alpha3 = "STP"
num = 678

[[countries]]
country = "Saudi Arabia"
alpha2 = "SA"
alpha3 = "SAU"
num = 682

[[countries]]
country = "Senegal"
alpha2 = "SN"
alpha3 = "SEN"
num = 686

[[countries]]
country = "Serbia"
alpha2 = "RS"
alpha3 = "SRB"
num = 688

[[countries]]
country = "Seychelles"
alpha2 = "SC"
alpha3 = "SYC"
num = 690

[[countries]]
country = "Sierra Leone"
alpha2 = "SL"
alpha3 = "SLE"
num = 694

[[countries]]
country = "Singapore"
alpha2 = "SG"
alpha3 = "SGP"
num = 702

[[countries]]
country = "Sint Maarten (Dutch part)"
alpha2 = "SX"
alpha3 = "SXM"
num = 534

[[countries]]
country = "Slovakia"
alpha2 = "SK"
alpha3 = "SVK"
num = 703

[[countries]]
country = "Slovenia"
alpha2 = "SI"
alpha3 = "SVN"
num = 705

[[countries]]
country = "Solomon Islands"
alpha2 = "SB"
alpha3 = "SLB"
num = 90

[[countries]]
country = "Somalia"
alpha2 = "SO"
alpha3 = "SOM"
num = 706

[[countries]]
country = "South Africa"
alpha2 = "ZA"
alpha3 = "ZAF"
num = 710

[[countries]]
country = "South Georgia and the South Sandwich Islands"
alpha2 = "GS"
alpha3 = "SGS"
num = 239

[[countries]]
country = "South Sudan"
alpha2 = "SS"
alpha3 = "SSD"
num = 728

[[countries]]
country = "Spain"
alpha2 = "ES"
alpha3 = "ESP"
num = 724

[[countries]]
country = "Sri Lanka"
alpha2 = "LK"
alpha3 = "LKA"
num = 144

[[countries]]
country = "Sudan (the)"
alpha2 = "SD"
alpha3 = "SDN"
num = 729

[[countries]]
country = "Suriname"
alpha2 = "SR"
alpha3 = "SUR"
num = 740

[[countries]]
country = "Svalbard and Jan Mayen"
alpha2 = "SJ"
alpha3 = "SJM"
num = 744

[[countries]]
country = "Sweden"
alpha2 = "SE"
alpha3 = "SWE"
num = 752

[[countries]]
country = "Switzerland"
alpha2 = "CH"
alpha3 = "CHE"
num = 756

[[countries]]
country = "Syrian Arab Republic"
alpha2 = "SY"
alpha3 = "SYR"
num = 760

[[countries]]
country = "Taiwan (Province of China)"
alpha2 = "TW"
alpha3 = "TWN"
num = 158

[[countries]]
country = "Tajikistan"
alpha2 = "TJ"
alpha3 = "TJK"
num = 762

[[countries]]
country = "Tanzania, United Republic of"
alpha2 = "TZ"
alpha3 = "TZA"
num = 834

[[countries]]
country = "Thailand"
alpha2 = "TH"
alpha3 = "THA"
num = 764

[[countries]]
country = "Timor-Leste"
alpha2 = "TL"
alpha3 = "TLS"
num = 626

[[countries]]
country = "Togo"
alpha2 = "TG"
alpha3 = "TGO"
num = 768

[[countries]]
country = "Tokelau"
alpha2 = "TK"
alpha3 = "TKL"
num = 772

[[countries]]
country = "Tonga"
alpha2 = "TO"
alpha3 = "TON"
num = 776

[[countries]]
country = "Trinidad and Tobago"
alpha2 = "TT"
alpha3 = "TTO"
num = 780

[[countries]]
country = "Tunisia"
alpha2 = "TN"
alpha3 = "TUN"
num = 788

[[countries]]
country = "Turkey"
alpha2 = "TR"
alpha3 = "TUR"
num = 792

[[countries]]
country = "Turkmenistan"
alpha2 = "TM"
alpha3 = "TKM"
num = 795

[[countries]]
country = "Turks and Caicos Islands (the)"
alpha2 = "TC"
alpha3 = "TCA"
num = 796

[[countries]]
country = "Tuvalu"
alpha2 = "TV"
alpha3 = "TUV"
num = 798

[[countries]]
country = "Uganda"
alpha2 = "UG"
alpha3 = "UGA"
num = 800

[[countries]]
country = "Ukraine"
alpha2 = "UA"
alpha3 = "UKR"
num = 804

[[countries]]
country = "United Arab Emirates (the)"
alpha2 = "AE"
alpha3 = "ARE"
num = 784

[[countries]]
country = "United Kingdom of Great Britain and Northern Ireland (the)"
alpha2 = "GB"
alpha3 = "GBR"
num = 826

[[countries]]
country = "United States Minor Outlying Islands (the)"
alpha2 = "UM"
alpha3 = "UMI"
num = 581

[[countries]]
country = "United States of America (the)"
alpha2 = "US"
alpha3 = "USA"
num = 840

[[countries]]
country = "Uruguay"
alpha2 = "UY"
alpha3 = "URY"
num = 858

[[countries]]
country = "Uzbekistan"
alpha2 = "UZ"
alpha3 = "UZB"
num = 860

[[countries]]
country = "Vanuatu"
alpha2 = "VU"
alpha3 = "VUT"
num = 548

[[countries]]
country = "Venezuela (Bolivarian Republic of)"
alpha2 = "VE"
alpha3 = "VEN"
num = 862

[[countries]]
country = "Viet Nam"
alpha2 = "VN"
alpha3 = "VNM"
num = 704

[[countries]]
country = "Virgin Islands (British)"
alpha2 = "VG"
alpha3 = "VGB"
num = 92

[[countries]]
country = "Virgin Islands (U.S.)"
alpha2 = "VI"
alpha3 = "VIR"
num = 850

[[countries]]
country = "Wallis and Futuna"
alpha2 = "WF"
alpha3 = "WLF"
num = 876

[[countries]]
country = "Western Sahara"
alpha2 = "EH"
alpha3 = "ESH"
num = 732

[[countries]]
country = "Yemen"
alpha2 = "YE"
alpha3 = "YEM"
num = 887

[[countries]]
country = "Zambia"
alpha2 = "ZM"
alpha3 = "ZMB"
num = 894

[[countries]]
country = "Zimbabwe"
alpha2 = "ZW"
alpha3 = "ZWE"
num = 716

[[countries]]
country = "Åland Islands"
alpha2 = "AX"
alpha3 = "ALA"
num = 248

